services:
  # 1) PostgreSQL 資料庫
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    shm_size: 128mb
    environment:
      #預設user:posrgres
      #預設資料庫名稱:db
      - POSTGRES_PASSWORD=school  # 你自己的密碼（記得改掉）
    volumes:
      - db_data:/var/lib/postgresql/data #- db_data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d   # ★ 這裡放 schema
    ports:
      - "5432:5432"                    # 如果只給容器用，可以拿掉這行
    networks:
      - school-net

  # 2) Adminer：用來看 Postgres 的簡易 GUI
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"                    # http://127.0.0.1:8080
    depends_on:
      - db
    networks:
      - school-net

  # 3) n8n 服務
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5679:5679"                    # 在瀏覽器 http://127.0.0.1:5679 進 n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5679
      - N8N_PROTOCOL=http
      # ※ 下面這行只是給 Flask 用，不是 n8n 自己用
      #   Flask 在容器裡用 http://n8n:5679 連到 n8n
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db
    networks:
      - school-net

  # 4) 你的 Flask 後端
  school-backend:
    build:
      context: .                       # 有 Dockerfile、school.py、templates 的資料夾
      dockerfile: Dockerfile
    container_name: school-backend
    ports:
      - "5000:5000"                    # http://127.0.0.1:5000
    environment:
      - FLASK_ENV=production
      # 給 Flask 用，容器間用 service name n8n
      - N8N_BASE=http://n8n:5679

      # 給 Flask 連 Postgres 用
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=school
    depends_on:
      - db
    networks:
      - school-net

networks:
  school-net:
    driver: bridge

volumes:
  n8n_data:
  db_data: